name: Deploy Hono API
on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: |
          docker build -t lemons:latest .
          docker save lemons:latest -o lemons.tar

      - name: transfer docker image to vps
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "lemons.tar"
          target: "/home/${{ secrets.VPS_USER }}"
          strip_components: 1

      - name: deploy to vps
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # Ensure docker has right permissions
            sudo chown $USER:docker lemons.tar

            # Load the image
            sudo docker load < lemons.tar

            # Clean up existing container
            sudo docker stop lemons || true
            sudo docker rm lemons || true

            # Run new container
            sudo docker run -d --name lemons \
              --restart unless-stopped \
              -p 10014:3000 \
              lemons:latest

            # Clean up tar file
            rm lemons.tar
