name: Deploy Hono API
on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          sudo docker build \
            --build-arg POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            --build-arg POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            -t lemons .

      - name: Save Docker image as tar
        run: |
          sudo docker save lemons:latest -o lemons.tar
          sudo chmod 644 lemons.tar

      - name: Transfer Docker image to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "lemons.tar"
          target: "/tmp/"
          overwrite: true
          debug: true

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # Load the image
            cd /tmp
            docker load < lemons.tar

            # Stop and remove the existing container if it exists
            docker stop lemons || true
            docker rm lemons || true

            # Run the new container
            docker run -d --name lemons \
              --restart unless-stopped \
              -p 10014:3000 \
              lemons:latest

            # Create .env file with DATABASE_URL
            echo "DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}?schema=public" > /tmp/.env

            # Clean up tar file
            rm lemons.tar
