name: Deploy on Push

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          if ! [ -x "$(command -v docker-compose)" ]; then
            sudo apt-get update
            sudo apt-get install -y docker-compose
          fi

      - name: Build and run containers
        run: |
          docker-compose down
          docker-compose up -d
